version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/linux-monitoring-dashboard/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/ubuntu/linux-monitoring-dashboard/prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - alertmanager
      - node-exporter

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - /home/ubuntu/linux-monitoring-dashboard/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus

volumes:
  grafana-data:
