global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

# Load alerting rules
rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "local_vm"
    static_configs:
      - targets: ["192.168.247.128:9100"]

  - job_name: "aws_instance"
    static_configs:
      - targets: ["172.31.37.85:9100"]
